name: InvisibilityViewerReloaded
main: com.cyprias.invisibilityviewer.InvisibilityViewer
version: 0.1
depend: [ProtocolLib]

commands:
  iv:
    description: Invisibility Viewer
    usage: /<command>

permissions:
  iv.*:
    description: Grants access to all other permissions
    default: false
    children:
      iv.view: true
      iv.toggle: true
  iv.view:
    description: See all hidden entities
    default: false
  iv.toggle:
    description: Toggles status
    default: false
